### ISSUE TITLE
NetCreator Not Showing Up in Plugins Menu of C4D S26

### ISSUE THREAD

**Issue by animationintern** [FireKDragon/NetCreator#3]
Hello!

I can find the commands for NetCreator in Command Manager in Cinema 4D S26, but can't seem to find the icon in the Extensions Menu.
![commandmenu](https://user-images.githubusercontent.com/107573666/173886022-670b394b-1f43-46aa-8201-988365a5cd14.png)
![extensions](https://user-images.githubusercontent.com/107573666/173886023-27fd2596-f957-4110-9b8f-7dfac3c4cbca.png)

Do you have any idea of how to fix this?

**Comment by LewisOrton** [comment]
Hi, sorry I don't use C4D these days and I'm not so sure what's the problem, I'm afraid you will need to work it out yourself.

**Comment by LewisOrton** [comment]
Hi, sorry I don't use C4D these days and I'm not so sure what's the problem, I'm afraid you will need to work it out yourself.

**Comment by animationintern** [comment]
No worries. thanks for the quick reply.
